name: Check for new upstream version

# Controls when the action will run. 
on:
  schedule:
    - cron: '17 22 * * *'
  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update to latest upstream awscli
        run: ${GITHUB_WORKSPACE}/scripts/update_awscli.sh
