name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "23 10 * * *"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update to latest upstream awscli
        run: |
          cd ${GITHUB_WORKSPACE}
          git config --global user.email "github-actions"
          git config --global user.name "github-actions"
          AWSCLI_LATEST=$(wget -q -O- "https://pypi.org/rss/project/awscli/releases.xml" | grep -m1 -E '<title>[0-9]+.[0-9]+.[0-9]+</title>' | sed -E 's/(\s*)?<(\/)?title>//g')
          AWSCLI_CURRENT=$(grep "ENV AWSCLI_VERSION" Dockerfile | awk '{print $3}' | sed -e 's/"//g')
          if [[ "${AWSCLI_CURRENT}" != "${AWSCLI_LATEST}" ]]; then
            echo "update awscli from ${AWSCLI_CURRENT} to ${AWSCLI_LATEST}"
            sed -i -e "s/${AWSCLI_CURRENT}/${AWSCLI_LATEST}/" Dockerfile
            git commit -m"AWS CLI ${AWSCLI_LATEST}" .
            git push
            # create and push the tag
            git tag --annotate "${AWSCLI_LATEST}" -m"AWS CLI ${AWSCLI_LATEST}" --force
            git push origin "${AWSCLI_LATEST}" --force
          fi
